# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coding_challenge_development
  username: leonardo
  password: 5432
  reaping_frequency: 0

test:
  <<: *default
  database: coding_challenge_test
  username: leonardo
  password: 5432
  reaping_frequency: 0

production:
  <<: *default
  database: coding_challenge_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  reaping_frequency: 0
